<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-AMSBLU7" failures="1" tests="4" name="Tests" time="0.088" errors="0" timestamp="2023-04-13T14:46:51 IST">
  <testcase classname="logisticsDb.CalcTest" name="CanAddNumbersFromGivenData" time="0.012"/>
  <testcase classname="logisticsDb.CalcTest" name="CanAddNumbersFromGivenData" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [4] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [5]
at logisticsDb.CalcTest.CanAddNumbersFromGivenData(CalcTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- CanAddNumbersFromGivenData -->
  <testcase classname="logisticsDb.CalcTest" name="CanAddNumbersFromGivenData" time="0.002"/>
  <testcase classname="logisticsDb.CalcTest" name="CanAddNumbers" time="0.001"/>
</testsuite> <!-- Tests -->
